brain_two/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path("todos/", include("todos.urls")),
    
]

todos/urls.py
from django.urls import path
from todos.views import TodoListListView

path('/todos/', TodoListListView.as_view(), name = "todo_list")

todos/models.py
from django.db import models
from django.forms import DateTimeField

# Create your models here.
class TodoList(models.Model):
    name = models.CharField(max_length = 100)
    created_on = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

class TodoItem(models.Model):
    task = models.CharField(max_length = 100)
    due_date = models.DateTimeField(null=True, blank=True)
    is_completed = models.BooleanField(default=False)
    list = models.ForeignKey(
        "TodoList",
        related_name="items",
        on_delete=models.CASCADE)
    def __str__(self):
        return self.task

    

todos/views.py
from django.shortcuts import render
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from todos.models import TodoItem, TodoList

# Create your views here.
class TodoListListView(ListView):
    model = TodoList
    template_name = "todos/list.html"

class TodoItemListView(ListView):
    model = TodoList
    template_name = "todos/list.html"

class TodoListDetailView(DetailView):
    model = TodoList
    template_name = "todos/detail.html"

todos/templates/todos/create.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    
</body>
</html>

todos/templates/todos/delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    
</body>
</html>

todos/templates/todos/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    
</body>
</html>

todos/templates/todos/edit.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <header>
        <nav>
          <ul>
            <li>
              <a href="{% url 'todo_list' %}">My Lists</a>
            </li>
            <li>
              <a href="{% url 'tags_list' %}">Tags</a>
            </li>
            {% if user.is_authenticated %}
            {% comment %} <li>
              <a href="{% url 'meal_plan_list' %}">Meal Plans</a>
            </li> {% endcomment %}
            <li>
              <a href="{% url 'shopping_item_list' %}">
                Shop List ({{ user.shopping_items.all|length }})
              </a>
            </li>
            <li>
              <a href="{% url 'logout' %}">Logout</a>
            </li>
            {% else %}
            <li>
              <a href="{% url 'login' %}">Login</a>
            </li>
            {% endif %}
            {% if user.is_staff %}
            <li>
              <a href="{% url 'admin:index' %}">Admin</a>
            </li>
            {% endif %}
            <li>
              <a href="{% url 'recipe_new' %}">Write a recipe</a>
            </li>
          </ul>
        </nav>
        {% block pagination %}
        {% endblock pagination %}
      </header>
</body>
</html>

todos/templates/todos/list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Todo Lists</title>
</head>
<body>
    <header>
        <nav>
          <ul>
            
            <li>
              <a href="{% url 'tags_list' %}">Tags</a>
            </li>
            {% if user.is_authenticated %}
            {% comment %} <li>
              <a href="{% url 'meal_plan_list' %}">Meal Plans</a>
            </li> {% endcomment %}
            <li>
              <a href="{% url 'shopping_item_list' %}">
                Shop List ({{ user.shopping_items.all|length }})
              </a>
            </li>
            <li>
              <a href="{% url 'logout' %}">Logout</a>
            </li>
            {% else %}
            <li>
              <a href="{% url 'login' %}">Login</a>
            </li>
            {% endif %}
            {% if user.is_staff %}
            <li>
              <a href="{% url 'admin:index' %}">Admin</a>
            </li>
            {% endif %}
            <li>
              <a href="{% url 'recipe_new' %}">Write a recipe</a>
            </li>
          </ul>
        </nav>
        {% block pagination %}
        {% endblock pagination %}
      </header>
      <main> 
        {% for name in todolist_list %}
        <div>
            <h2>
                <a href="{% url 'todo_list_detail' todolist.pk %}">{{ todolist.name }}</a>
            </h2>
        </div>
      {% endfor %}
      </main>
</body>
</html>